### ISSUE TITLE
feature request - 404 with "bruh" moment

### ISSUE THREAD

**Issue by PsykeDady** [bottlesdevs/bottlesdevs.github.io#1]
Actually the "404" not found page it's almost nice, but you can improve with a really powerfull "bruh moment" joke.

i propose to change message from:
> 404 - Page not found
> Sorry but you found an empty bottle! Go back to the homepage.

to:
> Bruh! you cringed `:\`
> 404 - Page not found
> Sorry but you found an empty bottle! Go back to the homepage. 

I bring you to attention that "*cringed*" is the correct verb form of the past of **cringe** 
[source](https://www.dictionary.com/browse/cringe#:~:text=verb%20(used%20without%20object)%2C,a%20corner%20and%20started%20praying)

**Comment by francescomasala** [comment]
Approved!
